spring:
  application:
    name: user-management-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.keycloak.server-url}/realms/${app.keycloak.realm}

server:
  port: 8080

app:
  keycloak:
    admin:
      client-id: admin-cli
      client-secret: CU85xzYKr69gpvK5YEuQCOQ5BYXioI9a
    realm: savespendr
    server-url: http://localhost:9081
    groups:
      merchant-group-id: 48b367e2-930c-4004-9c29-8c6a7f626a9a
      user-group-id: 061087cb-41aa-47e1-92fe-71a1cadc5f1f

management:
  endpoints:
    web:
      exposure:
        include: health, info
  health:
    readiness-state:
      enabled: true  # Enable readiness state health check
    liveness-state:
      enabled: true  # Enable liveness state health check
  endpoint:
    sessions:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true